Dev luuuxxx
J-ZhengLi/custom-rust-dist pull request #7
Opened 2024-07-23 07:06 UTC by LuuuXXX

支持在不同环境中下载合适的 rustup-init 二进制

cc issue-https://github.com/J-ZhengLi/custom-rust-dist/issues/6

2024-07-23 07:11 UTC, LuuuXXX commented
@J-ZhengLi

2024-07-23 09:54 UTC, J-ZhengLi requested changes
~~~

2024-07-23 09:54 UTC, J-ZhengLi commented on Cargo.toml
> +version = "0.52.0"
文件结尾漏了回车

2024-07-23 09:54 UTC, J-ZhengLi commented on src/rustup.rs
> +    }
工具自身可能导致的情况尽量避免直接 panic，而且第一条 `parse.expect` 有可能会把导致panic的问题隐藏掉 (实际只有字符串无法转成url时panic, 但是这里会显示"无法初始化下载链接")

最好使用 `anyhow::Context`:

```rust
use anyhow::{Result, Context};
pub fn download(&self, dest: &Path) -> Result<()> {
        let download_url = url::Url::parse(&format!(
            "{}/{}/{}/{}",
            RUSTUP_UPDATE_ROOT, "dist", self.triple, RUSTUP_INIT
        ))
        .context("Failed to init rustup download url")?;
        download_from_start(RUSTUP_INIT, &download_url, dest).context("Failed to download rustup")
    }
```

2024-07-23 09:54 UTC, J-ZhengLi commented on src/utils/process.rs
> +}
这一堆都可以不要 (rustup 用这个是为了支持 test, 并且在windows上存在一些问题导致测试失败后清不掉修改的 PATH 变量。我们之后可以使用其它方法来实现。如果实在需要的话第四阶段再加也无妨)，`Process::var` 直接用 `env::var` 代替

所有调用 `Process` 的地方同理。

2024-07-23 09:54 UTC, J-ZhengLi commented on src/utils/triple.rs
> +        if let Ok(triple) = process.var("XUANWU_OVERRIDE_HOST_TRPLE") {
`env::var("XUANWU_OVERRIDE_HOST_TRPLE")`

2024-07-24 03:16 UTC, LuuuXXX commented
r? @J-ZhengLi

2024-07-24 03:23 UTC, J-ZhengLi commented
LGTM

2024-07-24 03:24 UTC, J-ZhengLi approved these changes

2024-07-24 03:24 UTC, merged